app:
  name: "Scaffold API"
  version: "1.0.0"

http:
  port: "8000"

logger:
  logLevel: "debug"

db:
  poolMax: 2
  username: "root"
  password: "root"
  dbName: "postgres"
  host: "localhost"
  dbPort: 5432
  sslMode: "disable"
  timezone: "UTC"
