app:
  name: "Scaffold API"
  version: "1.0.0"

http:
  port: "8000"

logger:
  logLevel: "debug"

database:
  poolMax: ${POOL_MAX:2}
  username: ${DB_USER:root}
  password: ${DB_PASSWORD:root}
  dbName: ${DB_NAME:localhost}
  dbPort: ${DB_PORT:5432}
  sslMode: ${DB_SSL:disable}
  dbTimezone: "UTC"
