app:
  name: "Scaffold API"
  version: "1.0.0"
  lang: "pt_BR"
  host: "localhost:4000"

http:
  port: "4000"

logger:
  logLevel: "debug"

db:
  region: "eu-west-1"
  endpoint: ""

stripe:
  pubKey: ""
  secretKey: ""

solarz:
  email: "comercial@solarguardservices.com.br"
  password: "sgs2024*"