definitions:
  controllerV1.HealthCheckResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: Retorna o status de saúde da aplicação
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllerV1.HealthCheckResponse'
      summary: Health Check
      tags:
      - Health
swagger: "2.0"
